bbichul/bbichul-spring-backend

src/main/resources/static/index.html
=> #4 docs: 띄워쓰기 수정2

src/main/java/site/bbichul/models/User.java, src/main/resources/static/js/main_page.js
dev
유저 테이블 길이 수정 및 email 값 Null true 하기
resolved #41
=> #41 feat: 유저테이블 길이 수정 및 이메일 null true 수정

.gitignore, src/main/java/site/bbichul/BbichulApplication.java, src/main/java/site/bbichul/controller/JwtAuthenticationFilter.java, src/main/java/site/bbichul/controller/TimeController.java, src/main/java/site/bbichul/dto/TimeRequestDto.java, src/main/java/site/bbichul/models/Time.java, src/main/java/site/bbichul/models/User.java, src/main/java/site/bbichul/repository/TimeRepository.java, src/main/java/site/bbichul/security/kakao/KakaoOAuth2.java, src/main/java/site/bbichul/security/kakao/KakaoUserInfo.java, src/main/java/site/bbichul/service/TimeService.java, src/main/java/site/bbichul/service/UserService.java, src/main/java/site/bbichul/utills/JwtTokenUtil.java, src/main/resources/app.properties, src/main/resources/application.properties, src/main/resources/static/index.html, src/main/resources/static/js/main_page.js, src/main/resources/static/js/modal.js
dev 
공부 시간 추가 저장 
resolved #24
=> #24 feat: 타이머 기능을 위한 기초 구조 잡기

src/main/java/site/bbichul/controller/TimeController.java, src/main/java/site/bbichul/dto/TimeRequestDto.java, src/main/java/site/bbichul/dto/UserDto.java, src/main/java/site/bbichul/models/CalendarMemo.java, src/main/java/site/bbichul/models/Team.java, src/main/java/site/bbichul/models/TeamCalendar.java, src/main/java/site/bbichul/models/TeamTask.java, src/main/java/site/bbichul/models/Time.java, src/main/java/site/bbichul/models/User.java, src/main/java/site/bbichul/models/UserCalendar.java, src/main/java/site/bbichul/models/UserInfo.java, src/main/java/site/bbichul/models/Wise.java, src/main/java/site/bbichul/repository/UserRepository.java, src/main/java/site/bbichul/service/TimeService.java, src/main/java/site/bbichul/service/UserService.java, src/main/resources/static/js/main_page.js, src/main/resources/static/main_page.html
=> #37 feat: 모델링 초안 및 연관관계(단방향)연결

src/main/java/site/bbichul/controller/TimeController.java, src/main/java/site/bbichul/dto/TimeRequestDto.java, src/main/java/site/bbichul/dto/UserDto.java, src/main/java/site/bbichul/models/CalendarMemo.java, src/main/java/site/bbichul/models/Team.java, src/main/java/site/bbichul/models/TeamCalendar.java, src/main/java/site/bbichul/models/TeamTask.java, src/main/java/site/bbichul/models/Time.java, src/main/java/site/bbichul/models/User.java, src/main/java/site/bbichul/models/UserCalendar.java, src/main/java/site/bbichul/models/UserInfo.java, src/main/java/site/bbichul/models/Wise.java, src/main/java/site/bbichul/repository/UserRepository.java, src/main/java/site/bbichul/service/TimeService.java, src/main/java/site/bbichul/service/UserService.java, src/main/resources/static/js/main_page.js, src/main/resources/static/main_page.html
dev
공부 시작시 boolean ture 찍힘
resolved  #47
=> #47 feat: 공부시작 시 DB에 True(시작) 찍히는 기능

src/main/java/site/bbichul/controller/TimeController.java, src/main/java/site/bbichul/dto/TimeRequestDto.java, src/main/java/site/bbichul/dto/UserDto.java, src/main/java/site/bbichul/models/Time.java, src/main/java/site/bbichul/security/UserDetailsServiceImpl.java, src/main/java/site/bbichul/service/TimeService.java, src/main/java/site/bbichul/service/UserService.java
dev
공부시작, 종료시 출퇴근으로 구분하는 boolean DB에 저장 
resolved #47
=> #47 feat:공부시작 시 DB에 True(시작) ,끝날 씨 False 로 출퇴근 구분 기능

src/main/resources/static/js/main_page.js
dev
날씨 api 국가 및 날씨 상태ID 주석 
)
resolved #23
=> #23 feat: 날씨 API 수정

build.gradle, src/main/java/site/bbichul/controller/GoalController.java, src/main/java/site/bbichul/controller/ResolutionController.java, src/main/java/site/bbichul/dto/GoalRequestDto.java, src/main/java/site/bbichul/dto/ResolutionRequestDto.java, src/main/java/site/bbichul/models/UserInfo.java, src/main/java/site/bbichul/repository/TimeRepository.java, src/main/java/site/bbichul/service/GoalService.java, src/main/java/site/bbichul/service/ResolutionService.java, src/main/resources/application.properties, src/main/resources/static/js/my_page.js
dev
mypage progressbar 및 목표 설정 api 구현
resolved #1
=> Feature/setting goal/11

src/main/java/site/bbichul/controller/TeamController.java, src/main/java/site/bbichul/repository/UserRepository.java, src/main/java/site/bbichul/service/TeamService.java, src/main/resources/application.properties, src/main/resources/static/js/team_page.js
dev
팀원 출결 상황 확인 및 팀 가입하기
resolved #65 #33
=> Feature/team page/33

src/main/java/site/bbichul/controller/TeamController.java, src/main/java/site/bbichul/models/Team.java, src/main/java/site/bbichul/service/TeamService.java, src/main/resources/static/js/team_page.js, src/main/resources/static/team_page.html
=>  #67 fix: 팀 페이지 중복확인 버튼 관련 에러

src/main/java/site/bbichul/controller/TeamController.java, src/main/java/site/bbichul/dto/TeamProgressbarResponseDto.java, src/main/java/site/bbichul/repository/TeamTaskRepository.java, src/main/java/site/bbichul/service/TeamService.java, src/main/resources/static/js/team_page.js
dev
팀 to do list 진행상황 그래프 추가
resolved #35
=> #35 feat:to to list 진행 상황 그래프 완료

src/main/java/site/bbichul/controller/UserApiController.java, src/main/java/site/bbichul/dto/UserDto.java, src/main/java/site/bbichul/models/User.java, src/main/java/site/bbichul/repository/UserRepository.java, src/main/java/site/bbichul/security/UserDetailsServiceImpl.java, src/main/java/site/bbichul/service/GraphService.java, src/main/java/site/bbichul/service/UserService.java, src/main/resources/application.properties, src/main/resources/static/js/my_page.js, src/main/resources/static/my_page.html
=> #10 feat: 회원탈퇴 기능

src/main/java/site/bbichul/controller/ChangeUsernameController.java, src/main/java/site/bbichul/dto/UsernameDto.java, src/main/java/site/bbichul/models/User.java, src/main/java/site/bbichul/repository/UserRepository.java, src/main/java/site/bbichul/service/ChangeUsernameService.java, src/main/resources/application.properties, src/main/resources/static/js/my_page.js
dev
마이페이지 닉네임 세터 구현
resolved #8
=> Feature/get id/8

.github/workflows/deploy.yml, src/main/java/site/bbichul/controller/ChangeUsernameController.java, src/main/java/site/bbichul/controller/GoalController.java, src/main/java/site/bbichul/controller/GraphController.java, src/main/java/site/bbichul/controller/ResolutionController.java, src/main/java/site/bbichul/service/GoalService.java, src/main/java/site/bbichul/service/GraphService.java, src/main/java/site/bbichul/service/ResolutionService.java, src/main/resources/application.properties, src/main/resources/bootstrap.yml
=> Feature/mypage api/83

src/main/java/site/bbichul/controller/TeamController.java
=> #84 feat: 팀페이지 리팩토링(url 수정)

src/main/java/site/bbichul/security/WebSecurityConfig.java
=> 배포: webSecurityConfig 수정

src/main/java/site/bbichul/dto/TimeRequestDto.java, src/main/java/site/bbichul/dto/UserDto.java, src/main/java/site/bbichul/models/User.java
release1.1
isStudying 테이블 변경
resolved #99
=> #99 feat: isStudying 테이블 studying 으로 변경

src/main/java/site/bbichul/service/GraphService.java
=> feat: graph기준시간을 초에서 분으로 변경

src/main/java/site/bbichul/controller/UserApiController.java, src/main/java/site/bbichul/service/TimeService.java, src/main/java/site/bbichul/service/UserService.java
=> #105 feat: 계정 복구 기능

src/main/java/site/bbichul/controller/TeamController.java, src/main/java/site/bbichul/models/TeamTask.java, src/main/java/site/bbichul/service/TeamService.java
dev
to do list task에 수정 버튼 및 수정 기능 추가
=> #110 feat:to do list task 수정 기능 추가

src/main/java/site/bbichul/service/TeamService.java
dev
teamService updateTask함수에 transactional 어노테이션 추가
resolved #110
=> fix: teamService 수정

src/main/java/site/bbichul/controller/HomeController.java, src/test/java/site/bbichul/BbichulApplicationTests.java
dev
홈컨트롤러 URL 및 테스트어플리케이션 코드 변경
resolved #127
=> #127 타임테스트 코드 작성후 깃허브액션 오류해결1

src/test/java/site/bbichul/service/GoalServiceTest.java
=> #124 feat: 목표설정 성공케이스 테스트

src/main/java/site/bbichul/models/CalendarMemo.java, src/main/java/site/bbichul/models/Team.java, src/main/java/site/bbichul/models/User.java, src/main/java/site/bbichul/models/UserCalendar.java, src/main/java/site/bbichul/repository/UserRepository.java, src/main/java/site/bbichul/utills/NaverScraping.java, src/main/java/site/bbichul/utills/UserDelete.java
=> #135 feat: 회원탈퇴 후 7일 경과시 정보 자동삭제

build.gradle, logback/apiLog(2021-12-22).log, src/main/java/site/bbichul/controller/HomeController.java, src/main/resources/application.properties, src/main/resources/logback-spring.xml
dev
error log slack에 알림 뜨게하기
resolved #139
=> #139 feat: slack에 알림 연동해 상태관리하기

.github/workflows/deploy.yml, src/main/java/site/bbichul/controller/HomeController.java
=> fix: homecontroller 수정

.github/workflows/docker.yml
=> #144 fix: yml 수정

.github/workflows/docker.yml, logback/apiLog(2021-12-23).log
dev
yml 파일에서 중복으로 있던 코드 삭제
resolved #144 #145
=> #144 fix: yml 중복 코드 삭제

.github/workflows/docker.yml
=> #144 fix: yml secrets 수정

logback/apiLog(2021-12-24).log, src/main/resources/application.properties, src/main/resources/logback-spring.xml
dev
fix: properties, logback-spring 수정
resolved #144
=> #144 fix: properties, logback-spring 수정

src/main/resources/application.properties, src/main/resources/logback-spring.xml
=> #144 fix: 주석 처리한거 수정

logback/apiLog(2021-12-30).log, src/main/java/site/bbichul/controller/MyTeamController.java, src/main/java/site/bbichul/service/MyTeamService.java
=> Feature/mypage team/167

logback/apiLog(2021-12-30).log, src/main/java/site/bbichul/controller/TeamController.java, src/main/java/site/bbichul/dto/TeamTaskRequestDto.java, src/main/java/site/bbichul/repository/TeamRepository.java, src/main/java/site/bbichul/service/TeamService.java, src/test/java/site/bbichul/service/TeamServiceTest.java
=> #166 feat:팀페이지 리팩토링

logback/apiLog(2021-12-30).log, src/test/java/site/bbichul/service/TeamServiceTest.java
dev
팀페이지 테스트 코드 주석처리
resolved #171
=> #171 feat: 팀 페이지 테스트 코드 주석처리

logback/apiLog(2021-12-30) 2.log, logback/apiLog(2021-12-30).log, src/main/java/site/bbichul/models/Team.java
dev
team table jsonignore 어노테이션 추가
=> fix: 팀페이지 에러 수정
